apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-for-arrt
provisioner: kubernetes.io/no-provisioner
parameters:
  type: gp2
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
