apiVersion: v1
kind: ConfigMap
metadata:
  name: mediamtx-config
  namespace: arrt
data:
  mediamtx.yml: |
    logLevel: info
    logDestinations: [stdout]
    logFile: mediamtx.log

    readTimeout: 10s
    writeTimeout: 10s
    
    writeQueueSize: 512
    
    udpMaxPayloadSize: 1472

    
    runOnConnect:
    
    runOnConnectRestart: no
    
    runOnDisconnect:

    
    authMethod: internal

    
    authInternalUsers:
      
      - user: any
        
        pass:
        
        ips: []
        
        permissions:
          
          - action: publish
            
            path:
          - action: read
            path:
          - action: playback
            path:

        
      - user: any
        pass:
        ips: ["127.0.0.1", "::1"]
        permissions:
          - action: api
          - action: metrics
          - action: pprof

    
    authHTTPAddress:
    
    authHTTPExclude:
      - action: api
      - action: metrics
      - action: pprof

    
    authJWTJWKS:

    
    api: yes
    
    apiAddress: :9997
    
    apiEncryption: no
    
    apiServerKey: server.key
    
    apiServerCert: server.crt
    
    apiAllowOrigin: "*"
    
    apiTrustedProxies: []

    
    metrics: no
    
    metricsAddress: :9998
    
    metricsEncryption: no
   
    metricsServerKey: server.key
    
    metricsServerCert: server.crt
    
    metricsAllowOrigin: "*"
    
    metricsTrustedProxies: []

    
    pprof: no
    
    pprofAddress: :9999
    
    pprofEncryption: no
    
    pprofServerKey: server.key
    
    pprofServerCert: server.crt
    
    pprofAllowOrigin: "*"
    
    pprofTrustedProxies: []

    
    playback: no
    
    playbackAddress: :9996
    
    playbackEncryption: no
    
    playbackServerKey: server.key
    
    playbackServerCert: server.crt
    
    playbackAllowOrigin: "*"
    
    playbackTrustedProxies: []

    
    rtsp: yes
    
    protocols: [udp, multicast, tcp]
    
    encryption: "no"
    
    rtspAddress: 0.0.0.0:8554
    
    rtspsAddress: :8322
    
    rtpAddress: :8000
    
    rtcpAddress: :8001
    
    multicastIPRange: 224.1.0.0/16
    
    multicastRTPPort: 8002
    
    multicastRTCPPort: 8003
    
    serverKey: server.key
    
    serverCert: server.crt
   
    rtspAuthMethods: [basic]

    
    rtmp: yes
    
    rtmpAddress: :1935
    
    rtmpEncryption: "no"
    
    rtmpsAddress: :1936
    
    rtmpServerKey: server.key
    
    rtmpServerCert: server.crt

    
    hls: yes
    
    hlsAddress: :8888
    
    hlsEncryption: no
    
    hlsServerKey: server.key
    
    hlsServerCert: server.crt
    
    hlsAllowOrigin: "*"
    
    hlsTrustedProxies: []
    
    hlsAlwaysRemux: no
    
    hlsVariant: lowLatency
    
    hlsSegmentCount: 7
    
    hlsSegmentDuration: 1s
    
    hlsPartDuration: 200ms
    
    hlsSegmentMaxSize: 50M
    
    hlsDirectory: ""
    
    hlsMuxerCloseAfter: 60s

    
    webrtc: yes
    
    webrtcAddress: :8889
   
    webrtcEncryption: no
    
    webrtcServerKey: server.key
    
    webrtcServerCert: server.crt
    
    webrtcAllowOrigin: "*"
    
    webrtcTrustedProxies: []
    
    webrtcLocalUDPAddress: :8189
   
    webrtcLocalTCPAddress: ""
    
    webrtcIPsFromInterfaces: yes
   
    webrtcIPsFromInterfacesList: []
    
    webrtcAdditionalHosts: []
    
    webrtcICEServers2:
      []
      
    webrtcHandshakeTimeout: 10s
    webrtcTrackGatherTimeout: 2s

    
    srt: yes
    
    srtAddress: :8890

   
    pathDefaults:
      
      source: publisher
      
      sourceFingerprint:
      
      sourceOnDemand: no
      
      sourceOnDemandStartTimeout: 10s
      
      sourceOnDemandCloseAfter: 10s
      
      maxReaders: 0
      
      srtReadPassphrase:
      
      fallback:

      
      record: no
      
      recordPath: ./recordings/%path/%Y-%m-%d_%H-%M-%S-%f
      
      recordFormat: fmp4
      
      recordPartDuration: 1s
      
      recordSegmentDuration: 1h
      
      recordDeleteAfter: 24h

     
      overridePublisher: yes
      
      srtPublishPassphrase:

      
      rtspTransport: automatic
      
      rtspAnyPort: no
      
      rtspRangeType:
      
      rtspRangeStart:

      
      sourceRedirect:

     
      rpiCameraCamID: 0
      
      rpiCameraWidth: 1920
      
      rpiCameraHeight: 1080
     
      rpiCameraHFlip: false
      
      rpiCameraVFlip: false
      
      rpiCameraBrightness: 0
      
      rpiCameraContrast: 1
      
      rpiCameraSaturation: 1
      
      rpiCameraSharpness: 1
      
      rpiCameraExposure: normal
      
      rpiCameraAWB: auto
      
      rpiCameraAWBGains: [0, 0]
      
      rpiCameraDenoise: "off"
      
      rpiCameraShutter: 0
      
      rpiCameraMetering: centre
      
      rpiCameraGain: 0
      
      rpiCameraEV: 0
      
      rpiCameraROI:
      
      rpiCameraHDR: false
      
      rpiCameraTuningFile:
      
      rpiCameraMode:
      
      rpiCameraFPS: 30
      
      rpiCameraIDRPeriod: 60
      
      rpiCameraBitrate: 1000000
      
      rpiCameraProfile: main
      
      rpiCameraLevel: "4.1"
      
      rpiCameraAfMode: continuous
      
      rpiCameraAfRange: normal
      
      rpiCameraAfSpeed: normal
      
      rpiCameraLensPosition: 0.0
      
      rpiCameraAfWindow:
      
      rpiCameraTextOverlayEnable: false
      
      rpiCameraTextOverlay: "%Y-%m-%d %H:%M:%S - MediaMTX"

      
      runOnInit:
      
      runOnInitRestart: no

      
      runOnDemand:
      
      runOnDemandRestart: no
      
      runOnDemandStartTimeout: 10s
      
      runOnDemandCloseAfter: 10s
      
      runOnUnDemand:

      
      runOnReady:
      
      runOnReadyRestart: no
      
      runOnNotReady:

      
      runOnRead:
     
      runOnReadRestart: no
      
      runOnUnread:

      
      runOnRecordSegmentCreate:

      
      runOnRecordSegmentComplete:

    
    paths:
      stream1:
        source: rtsp://deepstream-demo.arrt:8554/stream
      all_others: