apiVersion: v1
kind: Service
metadata:
  name: arrtfrontend-service
  namespace: arrt
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8082
      targetPort: 3000
      protocol: TCP
    - name: api
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: arrtfrontend
