apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: arrt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672
        - containerPort: 15672

---
#service for this deployment
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: arrt  
spec:
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672